package apilolpi;

import java.awt.Label;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class InterfaceGrafica extends javax.swing.JFrame {
    
   
    BuscaJogador busca = new BuscaJogador();
    
    
    public InterfaceGrafica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BuscarJogador = new javax.swing.JButton();
        SummonerNameForm = new javax.swing.JLabel();
        IDForm = new javax.swing.JLabel();
        LevelForm = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BuscarJogador.setText("Buscar Jogador");
        BuscarJogador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarJogadorActionPerformed(evt);
            }
        });

        SummonerNameForm.setText("SummonerName");

        IDForm.setText("ID");

        LevelForm.setText("Level");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(BuscarJogador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(146, 146, 146))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(SummonerNameForm, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(IDForm, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LevelForm, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(BuscarJogador)
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SummonerNameForm)
                    .addComponent(IDForm)
                    .addComponent(LevelForm))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        SummonerNameForm.getAccessibleContext().setAccessibleName("SummonerName");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarJogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarJogadorActionPerformed

        
        try {
            busca.BuscaJogador();
        } catch (IOException ex) {
            Logger.getLogger(InterfaceGrafica.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_BuscarJogadorActionPerformed
        
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarJogador;
    public static javax.swing.JLabel IDForm;
    public static javax.swing.JLabel LevelForm;
    public static javax.swing.JLabel SummonerNameForm;
    // End of variables declaration//GEN-END:variables
}
